pipeline {
    agent any
    stages {
        stage('Package') { 
            steps {     
                withCredentials([string(credentialsId: 'DockerHub', variable: 'TOKEN')]) { 
                    sh "docker login -u 'yungyunc' -p '$TOKEN' docker.io" 
                    sh "docker build -t jenkins_k8s:latest --tag yungyunc/jenkins_k8s:latest ." 
                    sh "docker push yungyunc/jenkins_k8s:latest" 
                } 
            } 
        }
    }
}
