stage('Package') { 
    steps {     
        withCredentials([string(credentialsId: 'DockerHub', variable: 'TOKEN')]) { 
            sh "docker login -u '<username>' -p '$TOKEN' docker.io" 
            sh "docker build -t jenkins_k8s:latest --tag <username>/jenkins_k8s:latest ." 
            sh "docker push <username>/jenkins_k8s:latest" 
        } 
    } 
}